jwt:
  secret: "DB8243984CDE219D2945A492B4767A4909ACD96AB6C109231E9FE8C79E1"
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-refresh

spring:
  data:
    redis:
      host: localhost
      port: 6379

kakao:
  auth:
    client-id: dc3741c4aaad93067048db400f8fff38
    redirect-uri: http://localhost:8080/auth/login/kakao